### ISSUE TITLE
Mobility promotion not properly implemented

### ISSUE THREAD

**Issue by SpacedOutChicken** [9kgsofrice/DeCiv#1]
As written, the Mobility promotion does not do anything, because there is no provision in the core code for "+2 Movement". (MapUnit.kt does recognize "+2 Visibility Range" and "+2 Range", but not movement). There is a way to get the desired effect: just put "+1 Movement" in the listed uniques twice, and the game will count each one and add both to the unit's movement.

**Comment by 9kgsofrice** [comment]
Thanks, I will update this for the next version :)
